# Generated by Django 4.1.3 on 2022-11-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="last_used",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="preference_repetition_multiplier",
        ),
        migrations.AddField(
            model_name="recipe",
            name="preference_priority",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="recipe",
            name="queue_value",
            field=models.IntegerField(default=0),
        ),
    ]
